In [1]:
import torch
torch.__version__

'2.0.1+cu117'

### Let's see about tensors

you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

In [2]:
ten7 = torch.rand(size=(7,7))

In [3]:
ten7


tensor([[0.1751, 0.7958, 0.4967, 0.3387, 0.6212, 0.3261, 0.1317],
        [0.6164, 0.8033, 0.1116, 0.4466, 0.9183, 0.0282, 0.6196],
        [0.9910, 0.9088, 0.1670, 0.8654, 0.1193, 0.8601, 0.6191],
        [0.9415, 0.7800, 0.4417, 0.4993, 0.3351, 0.8358, 0.1530],
        [0.4473, 0.0249, 0.3011, 0.3970, 0.3143, 0.1001, 0.9147],
        [0.6435, 0.3382, 0.6654, 0.5950, 0.3431, 0.5528, 0.2702],
        [0.0631, 0.0416, 0.0033, 0.8656, 0.6418, 0.0845, 0.8123]])

In [4]:
ten7.shape


torch.Size([7, 7])

In [5]:
ten2 = torch.rand(size=(1,7))


In [6]:
mul = ten7 @ ten2.T

In [7]:
mul

tensor([[1.1892],
        [0.9430],
        [1.8683],
        [1.6662],
        [1.0388],
        [1.5015],
        [0.8059]])

In [9]:
torch.random.manual_seed(seed=0)

In [10]:
ten7 = torch.rand(size=(7,7))
ten2 = torch.rand(size=(1,7))
mul = ten7 @ ten2.T
mul

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [11]:
torch.cuda.is_available()


True

In [15]:
torch.cuda.current_device()


0

In [16]:
torch.cuda.device_count()

1

In [17]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce MX110'

In [18]:
device = torch.device('cuda')

In [19]:
device

device(type='cuda')

In [20]:
torch.random.manual_seed(seed=1234)

In [21]:
torch.cuda.seed?

In [23]:
torch.cuda.random.manual_seed(seed=1234)

In [30]:
new1 = torch.rand(size=(2,3)).to(device)
new2 = torch.rand(size=(2,3)).to(device)
print(new1,"\n",new2)
new_mul = new1 @ new2.T
print("MUL",new_mul)
new = torch.rand(size=(2,3))
new.device

tensor([[0.5274, 0.6325, 0.0910],
        [0.2323, 0.7269, 0.1187]], device='cuda:0') 
 tensor([[0.3951, 0.7199, 0.7595],
        [0.5311, 0.6449, 0.7224]], device='cuda:0')
MUL tensor([[0.7328, 0.7537],
        [0.7052, 0.6779]], device='cuda:0')


device(type='cpu')

In [37]:
X = torch.rand(size=(1,1,1,10))
print(X.shape)
X

torch.Size([1, 1, 1, 10])


tensor([[[[0.8733, 0.3230, 0.7917, 0.5447, 0.6220, 0.1668, 0.3932, 0.8298,
           0.7293, 0.3554]]]])

In [38]:
x = X.squeeze().squeeze()
print(x.shape)
x

torch.Size([10])


tensor([0.8733, 0.3230, 0.7917, 0.5447, 0.6220, 0.1668, 0.3932, 0.8298, 0.7293,
        0.3554])